const EVENTS = {
	connection: 'connection',
	CLIENT: {
		CREATE_CHAT_ROOM: 'CREATE_ROOM',
		SEND_ROOM_MESSAGE: 'SEND_ROOM_MESSAGE',
		JOIN_ROOM: 'JOIN_ROOM',
	},
	SERVER: {
		ROOMS: 'ROOMS',
		ROOM: 'ROOM',
		SEND_MESSAGE: 'SEND_ROOM_MESSAGE',
		JOINED_ROOM: 'JOINED_ROOM',
		ROOM_MESSAGES: 'ROOM_MESSAGES',
	},
};

export default EVENTS;
